# Generated by Django 3.2.20 on 2024-02-10 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(blank=True, default='', null=True, upload_to='uploads')),
                ('name', models.CharField(blank=True, default='', max_length=100, null=True)),
            ],
        ),
    ]
