# Generated by Django 3.2.20 on 2024-02-10 15:29

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0003_blog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('description', tinymce.models.HTMLField()),
                ('date', models.DateField(auto_now=True)),
                ('status', models.IntegerField(choices=[(0, 'Active'), (1, 'Done')], default=0)),
            ],
        ),
    ]
