# Generated by Django 3.2.20 on 2024-02-10 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0005_ticket_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='title',
            new_name='subject',
        ),
    ]
