# Generated by Django 3.2.20 on 2024-02-10 16:10

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0006_rename_title_ticket_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='reply',
            field=tinymce.models.HTMLField(default=''),
        ),
    ]
